cs50reader/views/auth.py
from util.helpers import apology, login_required
from sqlalchemy import select

from flask import (
    Blueprint, flash, redirect, render_template, request, Response, session
)

import json

from db.models import User
from db.db import get_db

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.route("/login", methods=["GET", "POST"])
async def login():
    """Log user in"""

    # Forget any user_id
    session.clear()

    # User reached route via POST (as by submitting a form via POST)
    if request.method == "POST":
        # Ensure username was submitted
        if not request.form.get("username"):
            return apology("must provide username", 403)

        # Ensure password was submitted
        elif not request.form.get("password"):
            return apology("must provide password", 403)

        async with get_db() as db_session:
            result = await db_session.execute(select(User).where(
                User.username == request.form.get("username")))
            user = result.scalars().one_or_none()

            await db_session.close()

        # Ensure username exists and password is correct
        if not isinstance(user, User) or not user.check_password(request.form.get("password")):
            return apology("invalid username and/or password", 403)

        # Remember which user has logged in
        session["user_id"] = user.id

        # Redirect user to home page
        return redirect("/")

    # User reached route via GET (as by clicking a link or via redirect)
    return render_template("login.html")

@auth_bp.route("/logout")
def logout():
    """Log user out"""

    # Forget any user_id
    session.clear()

    # Redirect user to login form
    return redirect("/")

@auth_bp.route("/register", methods=["GET", "POST"])
async def register():
    """Register user"""
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        confirm_password = request.form.get("confirmation")

        # Ensure username was submitted
        if not username:
            return apology("must provide username", 400)
        # Ensure password was submitted
        elif not password or not confirm_password:
            return apology("must provide password", 400)
        elif password != confirm_password:
            return apology("passwords must match", 400)

        async with get_db() as db_session:
            try:
                user = User()
                user.username = username
                user.set_password(password)
                await db_session.add(user)
                await db_session.commit()
            except:
                await db_session.close()
                return apology("Username already exists", 400)

            flash('You have successfully registerd!')
            await db_session.close()
            return redirect("/login")

    return render_template("register.html")


@auth_bp.route("/change_password", methods=["POST"])
@login_required
async def change_password():
    """Change user password"""
    user_id = session["user_id"]
    request_data = request.get_json()
    current_password = request_data['current_password']
    new_password = request_data['new_password']
    confirm_password = request_data['confirm_password']

    async with get_db() as db_session:
        user = await db_session.get(User, user_id)

        # check that the current password matches
        if not user.check_password(current_password):
            await db_session.close()
            return Response(json.dumps({'status': 'failure', 'error': 'bad password'}), status=400, mimetype='application/json')

        if new_password == '' or confirm_password == '':
            await db_session.close()
            return Response(json.dumps({'status': 'failure', 'error': 'password blank'}), status=400, mimetype='application/json')

        # check that the new password and confirmation match each other
        if not new_password == confirm_password:
            await db_session.close()
            return Response(json.dumps({'status': 'failure', 'error': 'password mismatch'}), status=400, mimetype='application/json')

        # create a new hash, and update the users table
        try:
            user.set_password(new_password)
            await db_session.commit()
            await db_session.close()
            return Response(response=json.dumps({'status': 'success'}), status=200, mimetype='application/json')
        except:
            pass

        await db_session.close()
    return Response(response=json.dumps({'status': 'failure'}), status=400, mimetype='application/json')

cs50reader/views/feed.py
from util.helpers import login_required
from sqlalchemy import select, insert, update, delete, distinct, and_, or_, func
import json, subprocess, time, logging
import asyncio, html, dateutil
from datetime import datetime, timedelta, timezone

from zoneinfo import ZoneInfo

import feedparser
from bs4 import BeautifulSoup, Comment
import os, time, argparse
from db.models import Feed, Article

import asyncio
import click
from flask import (
    Blueprint, redirect, Response, request, session, jsonify
)

import feedparser
from bs4 import BeautifulSoup
from db.models import User, Feed, Article, JT_User_Feed, JT_Feed_Article
from db.db import get_db

if os.environ.get('FLASK_DEBUG') == '1':
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)
#logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)
logger = logging.getLogger(__name__)

feed_bp = Blueprint('feed', __name__, url_prefix='/feed')

@feed_bp.route("/fetch_feeds", methods=["POST"])
@login_required
async def fetch_feeds():
    """ Get the list of feeds """
    user_id = session["user_id"]
    # return the feeds for the current user.
    feeds = None

    async with get_db() as db_session:

        result = await db_session.execute(select(Feed).join(JT_User_Feed, Feed.id == JT_User_Feed.feed_id).join(User, JT_User_Feed.user_id == User.id).where(User.id == user_id).order_by(Feed.title))
        feeds = result.scalars().fetchall()
        await db_session.close()

    if feeds is not None:
        return jsonify([{'id': f.id, 'title': f.title} for f in feeds])
    else:
        return jsonify({})


@feed_bp.route("/add_feed", methods=["POST"])
@login_required
async def add_feed():
    """ Add a feed """
    user_id = session["user_id"]
    request_data = request.get_json()
    feed_url = request_data.get('feed_url', None)
    feed_id = None

    async with get_db() as db_session:
        image_url = ''

        if feed_url:
            f = feedparser.parse(feed_url)

            if f.feed == {}:
                # the feed is bad.
                await db_session.close()
                return Response(json.dumps({'status': 'failure', 'message': 'bad feed'}), status=400, mimetype='application/json')

            # don't allow duplicate feeds
            result = await db_session.execute(select(Feed).join(JT_User_Feed, JT_User_Feed.feed_id == Feed.id).join(User, JT_User_Feed.user_id == User.id).where(and_(Feed.url == feed_url, User.id == user_id)))
            if result.scalars().one_or_none() is not None:
                await db_session.close()
                return Response(json.dumps({'status': 'failure', 'error': 'feed exists'}), status=400, mimetype='application/json')

            if 'icon' in f.feed:
                image_url = f.feed.get('icon', '')
            elif 'image' in f.feed:
                image_url = f.feed.image.get('url', '')
            else:
                image_url = ''

            # add the feed.
            user = await db_session.get(User, user_id)
            if not isinstance(user, User):
                await db_session.close()
                return redirect("/login")

            result = await db_session.execute(select(Feed).where(Feed.url == feed_url))
            result = result.scalars().one_or_none()
            if not isinstance(result, Feed):
                result = await db_session.execute(insert(Feed).values(title=f.feed.title, url=feed_url, description=f.feed.description,
                            icon_url=image_url, last_modified=datetime.min).returning(Feed.id))
                feed = result.scalars().one_or_none()
                feed_user = await db_session.execute(insert(JT_User_Feed).values(feed_id=feed, user_id=user_id).returning(JT_User_Feed.id))
            else:
                feed_user = await db_session.execute(insert(JT_User_Feed).values(feed_id=result.id, user_id=user_id).returning(JT_User_Feed.id))

            await db_session.commit()
            try:
                feed_id = feed
            except:
                pass
            await db_session.close()

        if (feed):
            subprocess.run(["python", "-m", "flask", "feed", "update", "--id", str(feed_id)])
            time.sleep(2)
            return Response(response=json.dumps({'status': 'success', 'feed_id': feed_id}), status=200, mimetype='application/json')

    return Response(response=json.dumps({'status': 'failure'}), status=400, mimetype='application/json')


@feed_bp.route("/update_feed", methods=["POST"])
@login_required
async def update_feed():
    user_id = session["user_id"]
    request_data = request.get_json()
    feed_id = int(request_data.get('feed_id'))
    new_articles = list()


    async with get_db() as db_session:

        result = await db_session.execute(select(JT_User_Feed.id).join(User, JT_User_Feed.user_id == User.id).where(
            and_(JT_User_Feed.feed_id == feed_id, User.id == user_id)))

        user_feed = result.scalars().one_or_none()

        # this looks complicated, but we are using a single query to update the user's junction table

        # 1. get all the article ids currently in the user's junction table for this feed...
        ids_in_jt_query = (select(JT_Feed_Article.article_id).join(JT_User_Feed, JT_Feed_Article.feed_id == JT_User_Feed.id).join(User, JT_User_Feed.user_id == User.id).where(and_(JT_User_Feed.feed_id == feed_id, User.id == user_id)).scalar_subquery())

        # 2. get all the article ids that belong to this feed but aren't in the user's junction table...
        ids_not_in_jt_query = select(distinct(Article.id), user_feed, 0).join(Feed, Article.feed_id == Feed.id).where(and_(Feed.id == feed_id, Article.id.notin_(ids_in_jt_query)))

        # 3. insert all the ids into the user's junction table and return their article ids
        result = await db_session.execute(insert(JT_Feed_Article).from_select(["article_id", "feed_id", "is_read"], ids_not_in_jt_query).returning(JT_Feed_Article.article_id))

        await db_session.commit()
        new_articles = [x for x in result.scalars().all()]

        result = await db_session.execute(select(func.count(JT_Feed_Article.id)).join(JT_User_Feed, JT_Feed_Article.feed_id == JT_User_Feed.id).join(User, JT_User_Feed.user_id == User.id).where(and_(and_(JT_User_Feed.feed_id == feed_id, User.id == user_id), JT_Feed_Article.is_read == 0)))
        unread_articles = result.scalars().one()

        await db_session.close()

    len_new_articles = len(new_articles)

    if len_new_articles != 0:
        return Response(response=json.dumps({'status': 'success', 'count': len_new_articles, 'article_ids': new_articles, 'unread_articles': unread_articles}), status=200, mimetype='application/json')
    elif len_new_articles == 0:
        return Response(response=json.dumps({'status': 'unchanged', 'count': len_new_articles, 'article_ids': new_articles, 'unread_articles': unread_articles}), status=200, mimetype='application/json')

    return Response(response=json.dumps({'status': 'unchanged', 'count': 0, 'article_ids': []}), status=304, mimetype='application/json')


@feed_bp.route("/delete_feed", methods=["POST"])
@login_required
async def delete_feed():
    """ Delete the specified feed """
    user_id = session["user_id"]
    request_data = request.get_json()
    feed_id = request_data.get('feed_id', -1)

    async with get_db() as db_session:
        try:
            await db_session.execute(delete(JT_User_Feed).where(
                and_(JT_User_Feed.feed_id == feed_id, JT_User_Feed.user_id == user_id)))

            await db_session.commit()
            await db_session.close()
            return Response(response=json.dumps({'status': 'success'}), status=200, mimetype='application/json')
        except Exception as e:
            logger.info(e)

        await db_session.close()
    return Response(response=json.dumps({'status': 'failure'}), status=400, mimetype='application/json')


@feed_bp.route("/mark_feed_read", methods=["POST"])
@login_required
async def mark_feed_read():
    """ Mark the specified article as read """
    user_id = session["user_id"]
    request_data = request.get_json()

    feed_id = request_data.get('feed_id', -1)
    async with get_db() as db_session:
        try:
            sub_query = (select(JT_Feed_Article.id).join(Feed, JT_Feed_Article.feed_id == Feed.id).join(JT_User_Feed, JT_Feed_Article.feed_id == JT_User_Feed.id).join(
                User, JT_User_Feed.user_id == User.id).where(and_(JT_Feed_Article.feed_id == feed_id, User.id == user_id)).scalar_subquery())
            result = await db_session.execute(update(JT_Feed_Article).where(
                and_(JT_Feed_Article.is_read == 0, JT_Feed_Article.id.in_(sub_query))).values(is_read=1))

            await db_session.commit()
            await db_session.close()
            return Response(response=json.dumps({'status': 'success'}), status=200, mimetype='application/json')
        except Exception as e:
            await db_session.close()
            logger.info(e)
            return Response(response=json.dumps({'status': 'failure'}), status=400, mimetype='application/json')


async def update_feeds(feed_id):
    """ Refresh the articles in the feed(s) """
    async with get_db() as db_session:
        if feed_id is not None:
            result = await db_session.execute(select(Feed).where(Feed.id == feed_id))
        else:
            result = await db_session.execute(select(Feed))

        if feed_id:
            feeds = [result.scalars().one()]
        else:
            feeds = result.scalars().all()


        for f in iter(feeds):
            new_articles = [] # or were going to end up with duplicate articles!

            try:
                last_modified = f.last_modified.astimezone(timezone.utc)
            except:
                last_modified = datetime.fromtimestamp(0, timezone.utc)


            # don't update feeds more frequently than every 15 minutes
            try:

cs50reader/templates/apology.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <!-- https://memegen.link/ -->
    <!-- https://knowyourmeme.com/memes/grumpy-cat -->
    <img alt="{{ top }}" class="border img-fluid" src="https://api.memegen.link/images/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?background=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
{% endblock %}

cs50reader/templates/layout.html
<!DOCTYPE html>

<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1, width=device-width">

        <!-- http://getbootstrap.com/docs/5.3/ -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">


        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>

        <link href="{{ url_for('static', filename='favicon.ico') }}" rel="icon">

        <link href="{{ url_for('static', filename='styles.css') }}" rel="stylesheet">

        <title>CS50 Reader: {% block title %}{% endblock %}</title>

    </head>

    <body class="container-fluid">

        <nav class="bg-light border navbar navbar-expand-md navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/"><span class="blue">C</span><span class="red">S</span><span class="yellow">5</span><span class="green">0</span> <span class="red">Reader</span></a>
                <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar">
                    {% if session["user_id"] %}
                        <ul class="navbar-nav me-auto mt-2">
                            <li class="nav-item"><a class="nav-link link-primary" id="add_feed" href="{{ url_for('feed.add_feed') }}">Add Feed</a></li>
                            <li class="nav-item"><a class="nav-link link-primary" id="delete_feed" href="{{ url_for('feed.delete_feed') }}">Delete Feed</a></li>
                        </ul>
                        <ul class="navbar-nav ms-auto mt-2">
                            <li class="nav-item"><a class="nav-link link-primary" id="change_password" href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                            <li class="nav-item"><a class="nav-link link-primary" href="{{ url_for('auth.logout') }}">Log Out</a></li>
                        </ul>
                    {% else %}
                        <ul class="navbar-nav ms-auto mt-2">
                            <li class="nav-item"><a class="nav-link link-primary" href="{{ url_for('auth.register') }}">Register</a></li>
                            <li class="nav-item"><a class="nav-link link-primary" href="{{ url_for('auth.login') }}">Log In</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% if get_flashed_messages() %}
            <header>
                <div class="alert alert-primary mb-0 text-center" role="alert">
                    {{ get_flashed_messages() | join(" ") }}
                </div>
            </header>
        {% endif %}

        <main class="container-fluid py-5 text-center">
            {% block main %}{% endblock %}
        </main>

        <footer class="container-fluid mb-5">
            <form action="https://validator.w3.org/check" class="text-center" enctype="multipart/form-data" method="post" target="_blank">
                <input name="doctype" type="hidden" value="HTML5">
                <input name="fragment" type="hidden">
                <input alt="Validate" src="{{ url_for('static', filename='I_heart_validator.png') }}" type="image"> <!-- https://validator.w3.org/ -->
            </form>
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    // Adapted from https://stackoverflow.com/a/10162353
                    const html = '<!DOCTYPE ' +
                    document.doctype.name +
                    (document.doctype.publicId ? ' PUBLIC "' + document.doctype.publicId + '"' : '') +
                    (!document.doctype.publicId && document.doctype.systemId ? ' SYSTEM' : '') +
                    (document.doctype.systemId ? ' "' + document.doctype.systemId + '"' : '') +
                    '>\n' + document.documentElement.outerHTML;
                    document.querySelector('form[action="https://validator.w3.org/check"] > input[name="fragment"]').value = html;
                });
            </script>
        </footer>
</div>
    </body>

</html>

cs50reader/templates/login.html
{% extends "layout.html" %}

{% block title %}
    Log In
{% endblock %}

{% block main %}
    <form action="{{ url_for('auth.login') }}" method="post">
        <div class="mb-3">
            <input autocomplete="off" autofocus required class="form-control mx-auto w-auto" name="username" placeholder="Username" type="text">
        </div>
        <div class="mb-3">
            <input class="form-control mx-auto w-auto" required name="password" placeholder="Password" type="password">
        </div>
        <button class="btn btn-primary" type="submit">Log In</button>
    </form>
{% endblock %}

cs50reader/templates/password.html
{% extends "layout.html" %}

{% block title %}
    Change Password
{% endblock %}

{% block main %}
<form action="/change_password" method="post">
    <div class="mb-3">
        <input autocomplete="off" autofocus class="form-control mx-auto w-auto" required name="current_password" placeholder="Current Password" type="password">
    </div>
    <div class="mb-3">
        <input autocomplete="off" class="form-control mx-auto w-auto" required name="new_password" placeholder="New Password" type="password">
    </div>
    <div class="mb-3">
        <input class="form-control mx-auto w-auto" name="confirm_password" required placeholder="Confirm New Password" type="password">
    </div>
    <button class="btn btn-primary" type="submit">Change Password</button>
</form>
{% endblock %}

cs50reader/templates/register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block main %}
    <form action="/register" method="post">
        <div class="mb-3">
            <input autocomplete="off" autofocus required class="form-control mx-auto w-auto" name="username" placeholder="Username" type="text">
        </div>
        <div class="mb-3">
            <input required class="form-control mx-auto w-auto" name="password" placeholder="Password" type="password">
        </div>
        <div class="mb-3">
            <input required class="form-control mx-auto w-auto" name="confirmation" placeholder="Confirm Password" type="password">
        </div>
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
{% endblock %}